#!/bin/sh

#input 1 - cookbook a
a=$1
b=$2

echo $a

echo $b


#get version numbers of cookbooks


version_a=`grep "version" $a/metadata.rb`
version_b=`grep "version" $b/metadata.rb`

if [ "$version_a" != "$version_b" ]
  then
  echo "Different"
  echo "$a: $version_a"
  echo "$b: $version_b"
else
  echo "Version matches: $version_a"
fi



#print differences


#get list of files in cookbook a and b
#print differences

find_a=`cd $a && find .`
find_b=`cd $b && find .`


if [ "$find_a" != "$find_b" ]
  then
  echo "Directory contents are different"
else
  echo "Directory contents match"
fi



#foreach file in cookbook_a
# get filename
for f in $find_a; do
  echo
  echo "checking $a/$f against $b/$f"
  echo
  diff -y --suppress-common-lines $a/$f $b/$f
done
#compare it to the same filename in cookbook_b

#print the differences
